### ISSUE TITLE
Interpolate this issue and review for a solution for this

### ISSUE THREAD

**Issue by larce1212** [larce1212/mockupero-api#10]
<- GET /                                     (105ms)
<- GET /styles/importer.css                  (42ms)
<- GET /js/dependencies/sails.io.js          (19ms)
error: Grunt :: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by larce1212** [comment]
Another error log of this king of error

  at MockIncomingMessage.<anonymous> (D:\projects\mockup\mockupero-api\node_mod
les\sails\lib\router\index.js:410:5)
  at emitNone (events.js:91:20)
  at MockIncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:926:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

<- POST undefined                (16ms)
<- GET undefined                        (0ms)
<- GET undefined                         (4ms)
<- GET undefined              (3ms)
<- GET undefined             (3ms)
{ user: 'admin11@gmail.com',
  message: 'Lets review that this chat works',
  room: '57ed62fb00473374254250c2',
  id: '57ed65d8bcd3df742abed3c1',
  createdAt: '2016-09-29T19:04:56.556Z',
  updatedAt: '2016-09-29T19:04:56.556Z' }
<- POST undefined  (10ms)
<- GET /user                                 (30ms)
<- GET /                                     (27ms)
<- GET /styles/importer.css                  (16ms)
<- GET /js/dependencies/sails.io.js          (12ms)
error: Grunt :: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript
heap out of memory
