### ISSUE TITLE
Error while editing mockup design

### ISSUE THREAD

**Issue by kapit4n** [larce1212/mockupero-api#36]
Step to reproduce:
- have a project created
- have a mockup created
- open the mockup
- edit design
- save design
current behaviour
It throws this error
 {"data":{"error":"E_UNKNOWN","status":500,"summary":"Encountered an
 {"unexpected error","raw":{}},"status":500,"config":{"method":"PUT","transfor
 {"mRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback"
 {","data":{"project":{"name":"Project 1","description":"This is a project
 {"where I will work mockups","imgToShow":"","userId":"58c33d285ee671461ef98fa
 {"2","state":"New","type":"Design","createdAt":"2017-03-11T00:00:15.495Z","up
 {"datedAt":"2017-05-02T13:57:03.746Z","id":"58c33e0f5ee671461ef98fa4"},"owner
 {"":{"email":"admin22@gmail.com","createdAt":"2017-03-06T19:56:39.337Z","upda
 {"tedAt":"2017-03-09T18:54:15.779Z","firstName":"Admin22","lastName":"Last
 {"Name","username":"admin22","id":"58bdbef7311a776d1f712711"},"name":"Mockup 
 {"002","width":"880","height":"400","state":"New","description":"","imgToShow
 {"":"http://blogs.atlassian.com/news/2009/09/10/SimpleLoginScreen-thumb-250x1
 {"79.png","createdAt":"2017-03-23T15:55:32.817Z","updatedAt":"2017-05-02T13:5
 {"7:03.661Z","links":[],"id":"58d3eff4a3ea8ec436fde7a9"},"url":"http://localh
 {"ost:1337/mockup/58d3eff4a3ea8ec436fde7a9","headers":{"Accept":"application/
 {"json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"wi
 {"thCredentials":true},"statusText":"Internal Server Error"}

Expected result:
Save mockup design without throwing any error

**Comment by kapit4n** [comment]
Error: data and salt arguments required
    at /home/larce/projects/mockuper-api-fix/mockupero-api/node_modules/bcrypt/bcrypt.js:98:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: data and salt arguments required
    at /home/larce/projects/mockuper-api-fix/mockupero-api/node_modules/bcrypt/bcrypt.js:98:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
